# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/api.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fproto/api.proto\x1a\x1bgoogle/protobuf/empty.proto\"(\n\x11ScreenShotRequest\x12\x13\n\x0bwindow_name\x18\x01 \x01(\t\"#\n\x12ScreenShotResponse\x12\r\n\x05image\x18\x01 \x01(\x0c\"3\n\x14KeyboardEventRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x0e\n\x06\x61\x63tion\x18\x02 \x01(\t\"\xaf\x01\n\x11MouseEventRequest\x12\x0e\n\x06\x61\x63tion\x18\x01 \x01(\t\x12\t\n\x01x\x18\x02 \x01(\x03\x12\t\n\x01y\x18\x03 \x01(\x03\x12\r\n\x05\x65nd_x\x18\x04 \x01(\x03\x12\r\n\x05\x65nd_y\x18\x05 \x01(\x03\x12\x0e\n\x06\x62utton\x18\x06 \x01(\t\x12\x10\n\x08interval\x18\x07 \x01(\x01\x12\x11\n\tover_time\x18\x08 \x01(\x01\x12\x0e\n\x06length\x18\t \x01(\x03\x12\x11\n\tdirection\x18\n \x01(\t2\xca\x01\n\x11GUICatcherService\x12\x37\n\nScreenShot\x12\x12.ScreenShotRequest\x1a\x13.ScreenShotResponse\"\x00\x12@\n\rKeyboardEvent\x12\x15.KeyboardEventRequest\x1a\x16.google.protobuf.Empty\"\x00\x12:\n\nMouseEvent\x12\x12.MouseEventRequest\x1a\x16.google.protobuf.Empty\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.api_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SCREENSHOTREQUEST']._serialized_start=48
  _globals['_SCREENSHOTREQUEST']._serialized_end=88
  _globals['_SCREENSHOTRESPONSE']._serialized_start=90
  _globals['_SCREENSHOTRESPONSE']._serialized_end=125
  _globals['_KEYBOARDEVENTREQUEST']._serialized_start=127
  _globals['_KEYBOARDEVENTREQUEST']._serialized_end=178
  _globals['_MOUSEEVENTREQUEST']._serialized_start=181
  _globals['_MOUSEEVENTREQUEST']._serialized_end=356
  _globals['_GUICATCHERSERVICE']._serialized_start=359
  _globals['_GUICATCHERSERVICE']._serialized_end=561
# @@protoc_insertion_point(module_scope)
