# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from proto import api_pb2 as proto_dot_api__pb2


class GUICatcherServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ScreenShot = channel.unary_unary(
                '/GUICatcherService/ScreenShot',
                request_serializer=proto_dot_api__pb2.ScreenShotRequest.SerializeToString,
                response_deserializer=proto_dot_api__pb2.ScreenShotResponse.FromString,
                )
        self.KeyboardEvent = channel.unary_unary(
                '/GUICatcherService/KeyboardEvent',
                request_serializer=proto_dot_api__pb2.KeyboardEventRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.MouseEvent = channel.unary_unary(
                '/GUICatcherService/MouseEvent',
                request_serializer=proto_dot_api__pb2.MouseEventRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )


class GUICatcherServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ScreenShot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def KeyboardEvent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MouseEvent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GUICatcherServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ScreenShot': grpc.unary_unary_rpc_method_handler(
                    servicer.ScreenShot,
                    request_deserializer=proto_dot_api__pb2.ScreenShotRequest.FromString,
                    response_serializer=proto_dot_api__pb2.ScreenShotResponse.SerializeToString,
            ),
            'KeyboardEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.KeyboardEvent,
                    request_deserializer=proto_dot_api__pb2.KeyboardEventRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'MouseEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.MouseEvent,
                    request_deserializer=proto_dot_api__pb2.MouseEventRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'GUICatcherService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class GUICatcherService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ScreenShot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GUICatcherService/ScreenShot',
            proto_dot_api__pb2.ScreenShotRequest.SerializeToString,
            proto_dot_api__pb2.ScreenShotResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def KeyboardEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GUICatcherService/KeyboardEvent',
            proto_dot_api__pb2.KeyboardEventRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def MouseEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GUICatcherService/MouseEvent',
            proto_dot_api__pb2.MouseEventRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
